[package]
name = "generated"
version.workspace = true
edition.workspace = true

[dependencies]
erased-serde = "0.4.6"
log.workspace = true
serde.workspace = true
serde_json = "1.0.140"
simple_logger.workspace = true
someip_parse.workspace = true
